### ISSUE TITLE
Misaligned Button

### ISSUE THREAD

**Issue by anshika0987** [FOSS-Community/website-fossc#154] opened 2023-05-02 20:14 UTC
### Contact Details

g.anshikacreative@gmail.com

## And I made some changes to fix bug. I would like to submit them for review.
@Mr-Sunglasses @ak

![fossc](https://user-images.githubusercontent.com/123721290/235774183-6f922a4a-88ef-4ae8-8608-6760318171b0.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr-Sunglasses** [comment] 2023-05-02 20:19
@anshika0987 The issue is assigned to you LFG 👍🏻

**Closed** 2023-05-02 20:41 UTC
Labels: bug
