### ISSUE TITLE
[Bug]: Missing Calender and Contribute tab in mobile view.

### ISSUE THREAD

**Issue by nitesh815** [FOSS-Community/website-fossc#192] opened 2023-06-13 12:34 UTC
### Contact Details

niteshsrivastava801@gmail.com

### To add missing calender and contribute tabs in mobile view, which are already present in desktop view.  
Please assign me this issue. @Mr-Sunglasses 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mr-Sunglasses** [comment] 2023-06-14 05:39
@nitesh815 can you please elaborate this issue.

**Comment by nitesh815** [comment] 2023-06-14 10:44
![fosscumobileweb](https://github.com/FOSS-Community/website-fossc/assets/111012529/6eb71c6e-9ee8-4c13-b3a0-3a9427d16c35)
![Screenshot (12)](https://github.com/FOSS-Community/website-fossc/assets/111012529/d549a5c7-55ef-432e-b6b5-42e786c7edbc)
When I open Fosscu website in my mobile(1st image), there is no calender option in menu. Which present in desktop view (2nd image) because of media query.

**Comment by Mr-Sunglasses** [comment] 2023-06-15 15:54
Sure the issue is assigned to you go ahead

**Closed** 2023-07-27 22:18 UTC
Labels: bug
